// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFwdH8l-M1tsYckLg2JFnODJ1DI3iH0A',
    appId: '1:438502949622:web:ff7a2ea67f1be76f6a22d7',
    messagingSenderId: '438502949622',
    projectId: 'tkchatfinal',
    authDomain: 'tkchatfinal.firebaseapp.com',
    storageBucket: 'tkchatfinal.appspot.com',
    measurementId: 'G-K4JDZEZYTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BD_NEs0Avv2QUUoWm_ahq2LSmqjAYIA',
    appId: '1:438502949622:android:91358bdd1c6a534d6a22d7',
    messagingSenderId: '438502949622',
    projectId: 'tkchatfinal',
    storageBucket: 'tkchatfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM0mOe2tZg0o6_I2-LwVcOA9dijEe1P7w',
    appId: '1:438502949622:ios:9e881683e165483d6a22d7',
    messagingSenderId: '438502949622',
    projectId: 'tkchatfinal',
    storageBucket: 'tkchatfinal.appspot.com',
    androidClientId: '438502949622-o94ldf6mse74qb4vu8flkuuhujd369h5.apps.googleusercontent.com',
    iosClientId: '438502949622-8k9vpfcr8dr3u5kvmlctjao7ajf1t19u.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.tuncchat',
  );
}
